### ISSUE TITLE
Available for django form ?

### ISSUE THREAD

**Issue by Bingo8** [jerch/django-treewidget#10]
Hello, i am interested in this widget can be implied in the django form and presented in the template ?

**Comment by jerch** [comment]
As long as the field is a django-treebeard or django-mptt based database field - yes. Simply use a modelform instance, add it to your template context and render the assets + the form itself.

Arbitrary tree forming data will not work out of the box. For this you gonna have to write your own formatter and change `TreeSelectWidgetMixin.prepare_queryset` in a way, that your custom data source is respected.

**Comment by jerch** [comment]
Clsoing issue due to inactivity.
