### ISSUE TITLE
Horizontal scroll for large content

### ISSUE THREAD

**Issue by debnet** [jerch/django-treewidget#11]
I have a graphical issue when using tree widget: it overrides the maximum width allowed.

Here:
![image](https://user-images.githubusercontent.com/634832/50014875-7288ac80-ffc5-11e8-8de8-6057140ecef0.png)

Could we find a trick to avoid that? A horizon scrollbar? A tooltip on hover? Both?

Thanks.

**Comment by jerch** [comment]
Yeah thats the edge where tree widgets get unhandy. Only chance I see is to wrap overlong lines, but I think this will not work with the 'wholerow' plugin. You might want to try to disable it and give the outer container a max width.

**Comment by jerch** [comment]
Closing this issue. Feel free to open a new one if you still experience issues with overlong lines.
