### ISSUE TITLE
Django 3.0 compatibility

### ISSUE THREAD

**Issue by jphilip** [jerch/django-treewidget#12]
Hi there,
Would it be possible to support Django 3.0?
The only issue so far seems to be that django.utils.encoding.python_2_unicode_compatible was dropped. I could be replaced by the same functionality in the six package of python 2 compatibility could be dropped.

**Comment by jerch** [comment]
@jphilip Well I have not tested it myself with Django 2.2 or 3.0 yet. Does it still work there beside the `six` issue? Note that there are several possible breaking points that need to be tested:
- Does the field construction logic still work? Imho this did not change in Django with 2.2/3.0. Affected files: `fields.py`, maybe template files.
- Does it still integrate well with newer admin stylesheets? Not sure Django changed them, possibly affected `default.css`.
- Does it still work with updated tree model packages? The unified `TreeQuerySet` only implements `treebeard` and `mptt` hooks, affected file `tree.py`.
- Is the JS part still compatible to newer jQuery version delivered with newer Django versions? Is the workaround still needed, does it still work as described?
- Optional: `jstree` could use an update as well. Atm 3.3.4 is delivered, official repo lists 3.3.9 as current release. Affected files: `default.js`, `formatters.py`.

For the six part imho we should drop Python 2 and Django 1.11 support, both are beyond their official support cycle now.

If you want to tackle some issues listed above - sure thing, would be nice to see it being updated. If you have a good idea, how this package could be tested automatically without setting up expensive selenium tests - I am all ears. For the listed versions I did it manually in the past, which gets exhausting for multiple versions pretty soon.
