### ISSUE TITLE
Use of Mutation Events is deprecated. Use MutationObserver instead.

### ISSUE THREAD

**Issue by debnet** [jerch/django-treewidget#3]
When using the widget into some browser (i.e. Mozilla Firefox), I got the following warning.

> Use of Mutation Events is deprecated. Use MutationObserver instead.

![image](https://user-images.githubusercontent.com/634832/37473885-68267b38-286f-11e8-9ddb-04557696a50c.png)
(Mozilla Firefox debug console in french)

**Comment by jerch** [comment]
Addressed in #4 . Could you test it?

**Comment by jerch** [comment]
fixed in #4

**Comment by debnet** [comment]
Perfect, thank you !
