### ISSUE TITLE
Initial value behavior is wierd

### ISSUE THREAD

**Issue by debnet** [jerch/django-treewidget#9]
Sometimes, when passing initial value to form, the selected element acts wierd and display the wrong selected element (whereas the internal selected value is right!) and sometimes the widget displays 2 selected item even if only one can be selected.

initial = 3 (good display)
![image](https://user-images.githubusercontent.com/634832/38317748-15f54e7e-382e-11e8-93ff-214bba34e54e.png)

initial = 14 (wrong display)
![image](https://user-images.githubusercontent.com/634832/38317893-6685607c-382e-11e8-81f3-a3b24346caf5.png)
should be
![image](https://user-images.githubusercontent.com/634832/38317921-7602b716-382e-11e8-8297-a5c7082c51ed.png)

```
<select name="parent" class="form-control custom-select" id="id_parent">
  <option value="">---------</option>
  <option value="14">collecte de données clients</option>
  <option value="15" selected>enregistrement audio</option>
  <option value="16">enregistrement video</option>
  <option value="4">collecte de données salariés</option>
  <option value="6">collecte format numérique</option>
  <option value="10">disque partagé</option>
  <option value="5">collecte format papier</option>
  <option value="1">opération de communication</option>
  <option value="2">emailing</option>
  <option value="3">newsletter</option>
  <option value="11">scoring client</option>
  <option value="12">scoring de carte bancaire</option>
  <option value="13">scoring de crédit</option>
  <option value="7">stockage de données salariés</option>
  <option value="9">stockage format numérique</option>
  <option value="8">stockage format papier</option>
</select>
```

**Comment by jerch** [comment]
If the querysets are the same, prolly a problem with the values in `selected`. Looks like selected value gets wrongly split into separate digits as pk list ([15] vs. [1, 5]). Whats it's content?

**Comment by debnet** [comment]
Just passing an integer/string to initial. What details do you want? :)

**Comment by debnet** [comment]
Seems you are right. Initial value are split as an iterable whereas Django set the selected value correctly. Is it possible to have a emergency fix for this one?

**Comment by jerch** [comment]
Are you using Python3 by any chance? The problem arises here (https://github.com/netzkolchose/django-treewidget/blob/master/treewidget/fields.py#L63):

```python
        ...
        if not selected:
            selected = []
        elif not hasattr(selected, '__iter__'):
            selected = [selected]
        selected = [str(pk) for pk in selected]
        ...
```

Just tested it - under Python3 a string has an `__iter__` attribute, thats why the code wrongly splits the string into digits.

As a hotfix replace
```python
elif not hasattr(selected, '__iter__'):
```

with
```python
elif not isinstance(selected, str):
```

Gonna write a patch fot it.

**Comment by debnet** [comment]
Perfect! Works like a charm! You're a real life saver. ;)

```python
elif isinstance(selected, str) or not hasattr(selected, '__iter__'):
```
